### ISSUE TITLE
Bug: 403 when opening library dashboard as "guillermotest" team member

### ISSUE THREAD

**Issue by gviedma-aulasneo** [openedx/openedx-authz#120]
**Current behavior**
Opening the library dashboard URL for a library where the user "guillermo test" is a team member returns a 403.

**Expected behavior**
User can access the dashboard and see the Team Members list if the have "view team member" permission over thar library.

**Steps to reproduce**
1) Log in as the team member account “guillermotest” (pass: jajaSalu2) 
2) Open:
https://apps.singapore.edunext.cloud/admin-console/authz/libraries/lib:OpenedX:CSPROB  
3) Observe the 403 response.

**Comments**
This may be tied to missing Studio access. Access to this route should depend only on the “view team members” permission, not on Studio access. It is important to note that if you had the "Author" or "Admin" role in the previous version, you automatically gained access to the studio and library, and that behavior should remain unchanged.

**Comment by MaferMazu** [comment]
@gviedma-aulasneo I assigned myself to this issue. I removed the release blocker tag because the code cut happened.
I would like to wait a bit to have the final changes in stage and try to reproduce this behavior to see if it is a bug or something we already fixed. Thanks for your patience.

**Comment by mariajgrimaldi** [comment]
I tested and I think this was solved by deploying Mafer's PR. @gviedma-aulasneo: could you test again? Thanks!

**Comment by gviedma-aulasneo** [comment]
@MaferMazu @mariajgrimaldi I just tested. After granting the library_user role to my account I still get a 403 when trying to open the admin console dashboard for CSPROB (https://apps.singapore.edunext.cloud/admin-console/authz/libraries/lib:OpenedX:CSPROB) with gviedma@aulasneo.com.

I can enter Studio Authoring Home now, but CSPROB is not listed in the library tab for my user. (Using the Staff test user I can see it)

Happy to help test this in a synchronous session, let me know if I am missing any setup details or if more info would help.

**Comment by mariajgrimaldi** [comment]
@gviedma-aulasneo maybe I'm missing something in the use case.

Before the deployment, the `library_admin_user`, who has the *Library Admin* role for [lib:OpenedX:CSPROB](https://apps.singapore.edunext.cloud/admin-console/authz/libraries/lib:OpenedX:CSPROB), couldn’t access the dashboard due to the error I mentioned [here](https://github.com/openedx/openedx-authz/issues/120#issuecomment-3492129986).

I tested with `library_admin_user` because, in [this comment](https://github.com/openedx/openedx-authz/issues/120#issuecomment-3491739194), you mentioned that you used a user with the manage permission, and this one fits that description. After the deployment, that user can now access the Access Management dashboard directly.

For the library `lib:OpenedX:CSPROB`, these are the only role assignments:

<img width="1889" height="747" alt="Image" src="https://github.com/user-attachments/assets/99475ec3-30d4-4950-9ea1-64ddd50b603d" />

The user [gviedma@aulasneo.com](mailto:gviedma@aulasneo.com) has the *Library User* role, which, according to the implementation, doesn’t include permission to manage the library team. Could you confirm if this is the expected behavior?

For reference, I’m using [this document](https://openedx.atlassian.net/wiki/spaces/OEPM/pages/4840095745/Library+Roles+and+Permissions#Table-of-Roles-and-Permissions).

Regarding the filtering, you should be able to see it in the Library tab view. I’ll review this part as well.

**Comment by mariajgrimaldi** [comment]
@gviedma-aulasneo: I finally understood! Thanks for the patience :)

So the user _can_ view the library team but can't edit it, which is how it's currently working. We're going to keep an eye on the sandbox to confirm it's behaving as expected. Tomorrow I'll go through the other bug related to filtering.

**Comment by MaferMazu** [comment]
**This issue has two problems:**
The first one with the filter will be solved with: https://github.com/openedx/edx-platform/pull/37564
The second one with the hard-load #133
